### ISSUE TITLE
game crash, only mod mentioned being perplayerspawns

### ISSUE THREAD

**Issue by SpinnyBoiii** [vlad2305m/fabric-per-player-spawns#5]
was just walking around a bit experimenting other mods and then crashed with this crashlog:

Description: Exception ticking world

java.lang.IncompatibleClassChangeError: Class [J does not implement the requested interface dev.lambdacraft.perplayerspawns.access.InfoAccess
	at net.minecraft.class_3215.md425d3b$lambda$setupSpawning$0$1(class_3215.java:1636)
	at net.minecraft.class_3215$$Lambda$7025/362414448.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_3215.method_27907(class_3215.java:409)
	at net.minecraft.class_3215$$Lambda$7023/1355941445.query(Unknown Source)
	at net.minecraft.class_3215.redirect$bje000$setupSpawning(class_3215.java:1632)
	at net.minecraft.class_3215.method_14161(class_3215.java:361)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$6605/1660782010.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3215.md425d3b$lambda$setupSpawning$0$1(class_3215.java:1636)
	at net.minecraft.class_3215$$Lambda$7025/362414448.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_3215.method_27907(class_3215.java:409)
	at net.minecraft.class_3215$$Lambda$7023/1355941445.query(Unknown Source)
	at net.minecraft.class_3215.redirect$bje000$setupSpawning(class_3215.java:1632)
	at net.minecraft.class_3215.method_14161(class_3215.java:361)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Affected level --
Details:
	All players: 1 total; [class_3222['SpinnyBoiii'/148, l='ServerLevel[New World]', x=-226.79, y=70.39, z=406.82]]
	Chunk stats: ServerChunkCache: 4084
	Level dimension: minecraft:overworld
	Level spawn location: World: (184,68,255), Chunk: (at 8,4,15 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11033 game time, 11033 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 62795 (now: false), thunder time: 10385 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$6605/1660782010.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vlad2305m** [comment]
@SpinnyBoiii Can you give me your mod list

**Comment by SpinnyBoiii** [comment]
![image](https://user-images.githubusercontent.com/49210394/119733188-74831500-be79-11eb-81e1-6dca5510c422.png)
![image](https://user-images.githubusercontent.com/49210394/119733199-777e0580-be79-11eb-96c1-cfd629d01086.png)
![image](https://user-images.githubusercontent.com/49210394/119733208-7a78f600-be79-11eb-9035-a5cdc1ec03fc.png)

ima guess incompatability with a mod that brings custom mobs? 
could be AdventureZ's summoner mob seeing as the crash happened right as a thunderstorm started i think

**Comment by vlad2305m** [comment]
@SpinnyBoiii This is a lot of mods... Can you recreate the bug by using command `/weather thunder`? If yes, you could figure out which mod exactly is incompatible, or just zip your mod folder and send to me so I do it (don't want to download all this manually).

**Comment by SpinnyBoiii** [comment]
didnt have time till now, sorry.
it didnt work with the command, but i did notice the amount of mobspawns being quite high during the thunderstorm(at some point i saw 2 spiders and 2 baby zombies spawning at the same spot at the exact same time).
i did the kill command for all non-player entities(multiple times in a row while ignoring the first one as i did travel for a bit before) and it repeatedly killed 200+, respawning pretty much every hostile mob i could see at the time within 5s

**Comment by vlad2305m** [comment]
Then it was that classic unexplainable "something went wrong in RAM" that I can do nothing about
